# Generated by Django 4.1.2 on 2022-10-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_title', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_price', models.CharField(blank=True, max_length=20)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.productitem')),
            ],
        ),
    ]
