# Generated by Django 4.1.2 on 2022-10-07 20:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='product_title', unique=True),
        ),
    ]
