# Generated by Django 4.1.2 on 2022-10-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_details_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='product_category',
        ),
    ]
