# Generated by Django 4.1.2 on 2022-10-09 09:44

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_product_details_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_image',
            field=models.ImageField(upload_to=App.models.Product_details.namFile),
        ),
    ]
