# Generated by Django 4.1.2 on 2022-10-09 11:01

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_product_details_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='product_img1',
            field=models.ImageField(null=True, upload_to=App.models.Product_details.namFile),
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_img2',
            field=models.ImageField(null=True, upload_to=App.models.Product_details.namFile),
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_img3',
            field=models.ImageField(null=True, upload_to=App.models.Product_details.namFile),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_image',
            field=models.ImageField(null=True, upload_to=App.models.Product_details.namFile),
        ),
    ]
