# Generated by Django 3.2.16 on 2022-10-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20221018_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
