# Generated by Django 3.2.16 on 2022-10-10 04:49

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_product_details_product_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_img1',
            field=models.ImageField(blank=True, null=True, upload_to=App.models.Product_details.namFile),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to=App.models.Product_details.namFile),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_img3',
            field=models.ImageField(blank=True, null=True, upload_to=App.models.Product_details.namFile),
        ),
    ]
