# Generated by Django 3.2.16 on 2022-10-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20221010_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
