# Generated by Django 3.2.16 on 2022-10-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20221018_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='option_addres',
            new_name='optional_address',
        ),
    ]
