# Generated by Django 3.2.16 on 2022-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_product_details_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
